### ISSUE TITLE
Difference Schema <-> Collection

### ISSUE THREAD

**Issue by monomango-wieland-hilker** [directus-labs/directus-template-cli#38]
I am currently trying my hands on creating a more granular fetching and applying of data.
So far so good, it seems to be working as expected. There are some aspects that def. need to be done together ( i.E. flows&operation or permissions&roles.)

My question comes at the role of Schema and Collection. To me it seems like they should do the same thing. Update the Collection-Schema. 
LoadData seems to some more (in regard to other collections too.) but then why also handle collections when they should be handled by the schema?

**Comment by bryantgillespie** [comment]
Closing as the behavior of latest version is different.
We still extract the schema so that if can be used if needed. But the CLI now uses the individual collection, fields, and relations endpoints to support loading more than one template into a single Directus instance.
