### ISSUE TITLE
Issues when the PK isn't "id"

### ISSUE THREAD

**Issue by Jbmanllr** [directus-labs/directus-template-cli#42]
For languages collection for example, PK is "code", well the content loader doesn't load any language provided, therefore the entirety of the app content isn't loaded because translations can't find related language entry.

**Comment by bryantgillespie** [comment]
I'm assuming this when you try to use your own templates?

Makes sense because we actually have `id` hardcoded here. 

https://github.com/directus-community/directus-template-cli/blob/abef5c030ab841a7b22b1534c58042ec042f12d4/src/lib/load/load-data.ts#L29C9-L44C12

**Comment by Jbmanllr** [comment]
yes, considered its the languages collection created by directus itself i though it was worth accounting for it as an issue that should be looked into.

Any short term workaround?

**Comment by bryantgillespie** [comment]
> Any short term workaround?

Hmmm. As in right now? Probably just manually creating it.

Will try to review and get a fix within the next week or two.

**Comment by Jbmanllr** [comment]
ok well ill wait a week or two then :) thanks, looking forward to it !

**Comment by bryantgillespie** [comment]
Marking as closed since this was resolved in a previous release.
