### ISSUE TITLE
Add better error logs

### ISSUE THREAD

**Issue by bryantgillespie** [directus-labs/directus-template-cli#47]
Should added some better error logging for third party use cases where extensive testing is not done. IE users extracting and applying their own templates that could potentially have different schemas, primary keys, etc.

Like #46 for instance.

**Comment by fishuke** [comment]
I also get a similar error, there is no translation.

`Extracted files
Extracted users
Extracted roles
Extracted permissions
Extracted presets
 ›   Warning: Error extracting Translations:
Extracting template - from **** to .... !
    TypeError: first argument must be a string or instance of Error`

**Comment by bryantgillespie** [comment]
Adding proper logs in #63
