### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'status')

### ISSUE THREAD

**Issue by lyamsidev** [directus-labs/directus-template-cli#50]
### Description
When attempting to apply an official template using `directus-template-cli`, the process fails with a TypeError. This error occurs regardless of the version used (tested with 0.4.0, 0.4.1, 0.3.6, and '@latest'). The expected behavior is for the template application process to complete successfully without errors.

Error encountered:

Loading 46 files... !
    TypeError: Cannot read properties of undefined (reading 'status')
    
### Steps to Reproduce
1. Run the command `npx directus-template-cli@0.4.1 apply`.
2. Choose "Official templates" when prompted for the template type.
3. Select the "Headless CMS - Website" template.
4. Observe the TypeError.

### Expected Behavior
The template application process should be completed successfully, allowing the "Headless CMS - Website" template to be applied to the Directus project.

### Actual Behavior
The process fails with a TypeError related to an undefined property 'status', preventing the successful application of the template.

### Possible Solution
N/A

### Additional Context
- The issue persists across multiple versions of `directus-template-cli`, including 0.4.0, 0.4.1, 0.3.6, and '@latest'.
- The error specifically mentions a problem with reading 'status', which might indicate an issue with handling response objects from a network request or similar operation.

### Frequency
The issue occurs consistently when following the steps to reproduce with the mentioned versions of `directus-template-cli`.

**Comment by littlejacky** [comment]
@lyamsidev I have encountered the same problem, could you please advise me on how to solve it?

**Comment by littlejacky** [comment]
@lyamsidev What versions of "directus" and "directus-template-cli" are you using?  Is it in Docker?
