### ISSUE TITLE
Error: Cannot find module 'node:url' On Ubuntu

### ISSUE THREAD

**Issue by tecnicosya** [directus-labs/directus-template-cli#51]
Hi guys I try to follow the guides to install the cli but something is wrong.

**If run this:**
npx directus-template-cli@latest apply

**This is the log**
`root@jose-System:~# sudo npx directus-template-cli@latest apply
Need to install the following packages:
  directus-template-cli@latest
Ok to proceed? (y) y
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'directus-template-cli@0.4.2',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@directus/sdk@14.0.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@oclif/core@3.26.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@oclif/plugin-help@6.0.20',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@oclif/plugin-plugins@4.3.10',
npm WARN EBADENGINE   required: { node: '>=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'formdata-node@6.0.3',
npm WARN EBADENGINE   required: { node: '>= 18' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'knex@3.1.0',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'minimatch@9.0.4',
npm WARN EBADENGINE   required: { node: '>=16 || 14 >=14.17' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'consola@3.2.3',
npm WARN EBADENGINE   required: { node: '^14.18.0 || >=16.10.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'nypm@0.3.8',
npm WARN EBADENGINE   required: { node: '^14.16.0 || >=16.10.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'commander@10.0.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'execa@8.0.1',
npm WARN EBADENGINE   required: { node: '>=16.17' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'get-stream@8.0.1',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'human-signals@5.0.0',
npm WARN EBADENGINE   required: { node: '>=16.17.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'signal-exit@4.1.0',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:url'
Require stack:
- /root/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/args.js
- /root/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/index.js
- /root/.npm/_npx/623fa71c079d6ec8/node_modules/directus-template-cli/bin/run
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/root/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/args.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/args.js',
    '/root/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/index.js',
    '/root/.npm/_npx/623fa71c079d6ec8/node_modules/directus-template-cli/bin/run'
  ]
}
`
I'm running it under root user.

**Comment by bryantgillespie** [comment]
I wouldn't usually recommend running it under the root user. But it looks like the node version you have installed is v12. Try upgrading to the latest version of node.

![ScreenShot 2024-03-29 at 22 49 27@2x](https://github.com/directus-labs/directus-template-cli/assets/23302570/f68c7a1b-e412-4731-accf-eec6439f04d5)

**Comment by tecnicosya** [comment]
> I wouldn't usually recommend running it under the root user. But it looks like the node version you have installed is v12. Try upgrading to the latest version of node.
> 
> ![ScreenShot 2024-03-29 at 22 49 27@2x](https://private-user-images.githubusercontent.com/23302570/318161741-f68c7a1b-e412-4731-accf-eec6439f04d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Njg0ODYsIm5iZiI6MTcxMTc2ODE4NiwicGF0aCI6Ii8yMzMwMjU3MC8zMTgxNjE3NDEtZjY4YzdhMWItZTQxMi00NzMxLWFjY2YtZWVjNjQzOWYwNGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDAzMDk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwYTA2NjRmZDEyZjFiMzY5ZWU5ZWExYzk4NTc2MjY4Yjg4NDE2Yjg1ZDhiNzJlNjY5MDgzYmMzMTM3NWU3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s_T0SdNJjQWD_d2R-0FXzhkZ-j57QzulyLdPQdmxYr0)

Thank you.
Now I install NVM and install 18 version and try again and get this:

`npx directus-template-cli@latest apply
Need to install the following packages:
directus-template-cli@0.4.2
Ok to proceed? (y) y
npm ERR! code ETIMEDOUT
npm ERR! syscall read
npm ERR! errno -110
npm ERR! network read ETIMEDOUT
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in: /home/jose/.npm/_logs/2024-03-30T03_05_46_207Z-debug-0.log
`


If try re-run I get this:
`npx directus-template-cli@latest apply
Need to install the following packages:
directus-template-cli@0.4.2
Ok to proceed? (y) y
node:internal/modules/cjs/loader:1143
  throw err;
  ^

Error: Cannot find module 'picomatch'
Require stack:
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/micromatch/index.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/utils/pattern.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/utils/index.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/managers/tasks.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/index.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/globby/index.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/plugin.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/plugin-loader.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/config.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/index.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/command.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/index.js
- /home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/directus-template-cli/bin/run
    at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
    at Module._load (node:internal/modules/cjs/loader:981:27)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/micromatch/index.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/micromatch/index.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/utils/pattern.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/utils/index.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/managers/tasks.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/fast-glob/out/index.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/globby/index.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/plugin.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/plugin-loader.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/config.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/config/index.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/command.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/@oclif/core/lib/index.js',
    '/home/jose/.npm/_npx/623fa71c079d6ec8/node_modules/directus-template-cli/bin/run'
  ]
}

Node.js v18.20.0
`

Now I'm running under my user.
The error say have network problems, but this not true!

**Comment by tecnicosya** [comment]
Ok I "solved" in my way.
1. Run this in new folder: npm i directus-template-cli
2. then I go to hidden folder where is downloaded: /home/jose/.npm/_npx/623fa71c079d6ec8/
3. Combine the files downloaded in step 1 the hidden folder.
4. Re-run: npx directus-template-cli@latest apply

And then all is ok, start the wizard.
