### ISSUE TITLE
File not found: fields.json

### ISSUE THREAD

**Issue by SiteEngineers** [directus-labs/directus-template-cli#54]
Was told by Directus Support (Jonathan) I could use this tool to migrate Directus from Microsoft SQL Server to PostgresSQL.
I can use the extract command with no issue to generate a template, but when I try to apply the template to the new server, I am met with the following error:

Error: File not found: C:\Github\directus-template-cli\templates\events\src\fields.json
    at readFile (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\directus-template-cli\dist\lib\utils\read-file.js:9:15)
    at checkTemplate (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\directus-template-cli\dist\lib\utils\check-template.js:10:48)
    at apply (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\directus-template-cli\dist\lib\load\index.js:23:61)
    at ApplyCommand.run (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\directus-template-cli\dist\commands\apply.js:125:34)
    at async ApplyCommand._run (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\@oclif\core\lib\command.js:311:22)
    at async Config.runCommand (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\@oclif\core\lib\config\config.js:433:25)
    at async Object.run (C:\Users\skid\AppData\Local\npm-cache\_npx\623fa71c079d6ec8\node_modules\@oclif\core\lib\main.js:92:16)
 »   Error: The template is missing the collections, fields, or relations files. Older templates are not supported in v0.4 of directus-template-cli. Try using v0.3 to load older templates
 »    npx directus-template-cli@0.3 apply or extract the template using latest version before applying. Exiting...

**Comment by bryantgillespie** [comment]
This error appears to be an issue with the extracted template missing some of the collections, fields, or relations.

**Comment by bryantgillespie** [comment]
Can you confirm there is a fields.json within the directory of the template you're trying to apply?

**Comment by bryantgillespie** [comment]
You can see the two calls here that filter out system filters.
https://github.com/search?q=repo%3Adirectus-labs%2Fdirectus-template-cli%20.system&type=code

It's trying to read the `meta` key for each field and/or relation and it's not receiving the data so it's throwing an error. 

The question is why is it not getting the fields and relation data. 

Without more context I'm not exactly sure where to tell you to look.

Here's just a few thoughts based on past experiences.

- What Directus version are you trying to extract from? Is it an older version?
- Are permissions configured correctly / are you using a token with Admin permissions to extract the template?
- Have you looked at the fields and relationships within the instance to ensure they are configured correctly?

**Comment by SiteEngineers** [comment]
I am on 10.10.7 and using the Admin token. 
I believe it's that we're hosting Microsoft SQL on Google's Cloud SQL and the account they give us is sa-like, but not sa (for obvious security reasons)
Could that be what's preventing access to system? Is there any way around that?

**Comment by bryantgillespie** [comment]
Hmm. I'm not so sure what it would be.

So long as you have access to instance (no CORS issues or firewall problems) and a token for a user that has an Administrator role - it should work ok.

I've not tested MS SQL in the past, but we did have issues when going from Postgres to MySQL. But that's only on the `apply` side. 

Whereas the problem here is happening on the `extract` side of the equation.

I'm not 100% on what to tell you to try next as I have not encountered this type of issue before.

Do you have any trace logs from the Directus server?

**Comment by SiteEngineers** [comment]
Here's the server log when I run extract.. gets 200 on /fields and I'm also able to hit that endpoint with no issue. 
Could I just hit those endpoints and right-click/save as json the files to the template /src folder as fields.json and relations.json?

`│ [16:44:46] GET /users/me 200 26ms                                                                                                                                                                              
│ [16:44:47] GET /schema/snapshot 200 414ms                                                                                                                                                                      
│ [16:44:47] GET /collections 200 23ms                                                                                                                                                                          
│ [16:44:46.936] WARN: Collection "BuClasses" doesn't have a primary key column and will be ignored                                                                                                              
│ [16:44:47] GET /fields 200 106ms                                                                                                                                                                               
│ [16:44:47] GET /relations 200 23ms                                                                                                                                                                             
│ [16:44:47] GET /fields 200 95ms                                                                                                                                                                                
│ [16:44:47] GET /folders?limit=-1 200 14ms                                                                                                                                                                      
│ [16:44:48] GET /files?limit=-1 200 18ms                                                                                                                                                                        
│ [16:44:48] GET /users?limit=-1 200 22ms                                                                                                                                                                        
│ [16:44:48] GET /roles?limit=-1 200 27ms                                                                                                                                                                        
│ [16:44:48] GET /permissions?limit=-1 200 24ms                                                                                                                                                                  
│ [16:44:48] GET /presets?filter=%7B%22user%22%3A%7B%22_null%22%3Atrue%7D%7D&limit=-1 200 19ms                                                                                                                   
│ [16:44:48] GET /translations?limit=-1 200 14ms                                                                                                                                                                 
│ [16:44:48] GET /flows?limit=-1 200 20ms                                                                                                                                                                        
│ [16:44:48] GET /operations?limit=-1 200 16ms                                                                                                                                                                   
│ [16:44:48] GET /dashboards?limit=-1 200 14ms                                                                                                                                                                   
│ [16:44:49] GET /panels?limit=-1 200 15ms                                                                                                                                                                       
│ [16:44:49] GET /settings?limit=-1 200 22ms                                                                                                                                                                     
│ [16:44:49] GET /collections 200 20ms                                                                                                                                                                           
│ [16:44:49] GET /items/articles?limit=-1 200 16ms                                                                                                                                                               
│ [16:44:49] GET /items/BuClasses?limit=-1 403 13ms                                                                                                                                                              
│ [16:44:49] GET /items/Campaigns?limit=-1 null 6ms`
