### ISSUE TITLE
Warning: Error extracting Fields:

### ISSUE THREAD

**Issue by D144679076-cmd** [directus-labs/directus-template-cli#55]
I was trying to extract my directus project to template when this is error appear:
'''
Logged in as Admin User
------------------
Attempting to create directory at: templates/test/src
Attempting to create directory at: templates/test/src/schema
Extracted schema snapshot
Extracted collections
 ›   Warning: Error extracting Fields:
 ›   Warning: Cannot read properties of null (reading 'system')
 ›   Warning: Error extracting Relations:
 ›   Warning: Cannot read properties of null (reading 'system')
Extracted folders
Extracted files
Extracted users
Extracted roles
Extracted permissions
Extracted presets
Extracted translations
Extracted flows
Extracted operations
Extracted dashboards
Extracted panels
Extracted settings
Extracted items from collection: classes
Extracted items from collection: classes_directus_users
Extracted items from collection: exams
Extracted items from collection: exams_classes
Extracted items from collection: exams_directus_users
Extracted items from collection: exams_question_list
Extracted items from collection: exams_result
Extracted items from collection: exercises
Extracted items from collection: exercises_classes
Extracted items from collection: exercises_directus_users
Extracted items from collection: exercises_result
Extracted items from collection: games
Extracted items from collection: games_classes
Extracted items from collection: games_directus_users
Extracted items from collection: games_results
Extracted items from collection: gpa_boards
Extracted items from collection: lessons
Extracted items from collection: levels
Extracted items from collection: manager_departments
Extracted items from collection: question_lists
Extracted items from collection: question_lists_questions
Extracted items from collection: questions
Extracted items from collection: schools
Extracted items from collection: sections
Extracted items from collection: subjects
Extracted items from collection: templates
Extracted items from collection: topics
Extracted items from collection: videos
Extracted items from collection: videos_classes
Extracted items from collection: videos_directus_users
Extracted items from collection: visiting_plans
All files have been downloaded.
Extracting template - from http://localhost:8080/api/ to templates/test... done
------------------
Template extracted successfully.
'''
i don't know how to fix it please help me

**Comment by bryantgillespie** [comment]
Almost impossible to debug without further context.
