### ISSUE TITLE
TypeError on export

### ISSUE THREAD

**Issue by ulysse-lacour** [directus-labs/directus-template-cli#65]
Hello, on a project when trying to export template I'm always getting this very non verbose error :

    Loading 92 files... !
    TypeError: The "paths[2]" argument must be of type string. Received null
    Code: ERR_INVALID_ARG_TYPE`

Any idea how could I debug/fix this ?

**Comment by ulysse-lacour** [comment]
Anyone ? Still stuck on exact same issue and couldn't find any way to export template...

**Comment by bryantgillespie** [comment]
Closing this one to tidy things up a bit, but please feel free to reopen if you're still having issues.
