### ISSUE TITLE
"Error: ENOENT: no such file or directory ... " issue inside docker container

### ISSUE THREAD

**Issue by sangdth** [directus-labs/directus-template-cli#67]
When I'm trying to run this
```
npx directus-template-cli@latest apply
```
in Dokploy service, I got this error:
```
Loading 76 collections and 700 fields... done
Loading 176 relations... done
Loading 4 roles... done
 ›   Warning: Unknown error: "File not found: 
 ›   /home/node/.npm/_npx/623fa71c079d6ec8/node_modules/directus-template-cli/d
 ›   ist/lib/downloads/official/agencyos/src/policies.json"
    Error: ENOENT: no such file or directory, open 
    '/home/node/.npm/_npx/623fa71c079d6ec8/node_modules/directus-template-cli/
    dist/lib/downloads/official/agencyos/src/policies.json'
    Code: ENOENT
```

More info:
- Using Dokploy (similar to EasyPanel, Coolify)
- Setup the Directus successfully, using [this guide](https://github.com/directus-labs/agency-os?tab=readme-ov-file#2---generate-a-static-token-for-the-admin-user) (step 1 and 2)
- When I tried to follow step 3, I got this issue.

**Comment by whereismyguts** [comment]
same error, 
using `npx directus-template-cli@latest apply`

**Comment by Kovoki** [comment]
> та же ошибка, используя`npx directus-template-cli@latest apply`

🚀

🍅

**Comment by sangdth** [comment]
After digging the github issues, I found out the CLI `latest` does not support the AgencyOS v.11 yet. So we have to use the previous version

This could work at this time:

```
npx directus-template-cli@0.4.3 apply
```

**Comment by bryantgillespie** [comment]
Closing in favor of tracking this in #68
